name: vitaminb
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - pandas=2.1.0
  - matplotlib=3.7.0
  - numpy=1.24.4
  - ffmpeg=6.1.0
  - pip=25.1
  - setuptools=80.1.0
  - wheel=0.45.1
  - jinja2=3.1.6
  - pyyaml=6.0.2
  - psutil=7.0.0
  - filelock=3.18.0
  - tqdm=4.65.0
  - sympy=1.14.0
  - networkx=3.2.1
  - numexpr=2.10.1
  - pytz=2025.2
  - ca-certificates
  - openssl
  - pip:
      - accelerate==0.24.0
      - addict==2.4.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - av==14.4.0
      - blinker==1.9.0
      - catkin-pkg==1.0.0
      - cffi==1.17.1
      - chardet==5.2.0
      - click==8.1.8
      - comm==0.2.2
      - configargparse==1.7.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - dash==3.0.4
      - decorator==5.2.1
      - defusedxml==0.7.1
      - diffusers==0.18.2
      - dill==0.3.7
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docutils==0.21.2
      - easyocr==1.7.2
      - einops==0.6.1
      - empy==4.2
      - entrypoints==0.4
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fasteners==0.19
      - fastjsonschema==2.21.1
      - flask==3.0.3
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - hf-xet==1.1.3
      - huggingface-hub==0.33.0
      - hydra-core==1.2.0
      - imagecodecs==2023.9.18
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - llvmlite==0.40.1
      - numba==0.57.0
      - narwhals==1.41.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - netifaces==0.11.0
      - ninja==1.13.0
      - numcodecs==0.11.0
      - open3d-cpu==0.19.0
      - opencv-python-headless==4.7.0.72
      - packaging==25.0
      - parso==0.8.4
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.8
      - plotly==6.1.2
      - prompt-toolkit==3.0.51
      - protobuf==4.25.7
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyclipper==1.3.0.post6
      - pycparser==2.22
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - pyserial==3.5
      - python-bidi==0.6.6
      - referencing==0.36.2
      - regex==2024.11.6
      - reportlab==4.4.1
      - requests==2.32.3
      - retrying==1.3.4
      - rospkg==1.5.1
      - rpds-py==0.25.1
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - shapely==2.0.7
      - smmap==5.0.2
      - stack-data==0.6.3
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - timm==0.9.7
      - traitlets==5.14.3
      - typing-extensions==4.13.2
      - wandb==0.15.8
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - zarr==2.16.0
      - zipp==3.21.0
      - opencv-contrib-python==4.7.0.72